### ISSUE TITLE
Check if Scan Result is ok

### ISSUE THREAD

**Issue by Jan-Malte-W** [Haldoryn/Kartierung-eines-Raums#8]
For The RobotInteraction Handler it is necessary to implement that the robo do only the next Move, if the Scan Result is ok (see Config). Then the Alternative moving algo in the Controlling class can be outcommented

**Comment by Haldoryn** [comment]
I implemented the checkScan method for this task. It returns a boolean. the alternative moving algo was slightly changed in order to fit with the boolean. I had to do it because the chackScan method does 3 scans. One in the middle, one tan((WheelDistance/2)/MovingDistance) deg to the right and one tan((WheelDistance/2)/MovingDistance) deg to the left, in order to be really sure that the robot does fit.
